AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

Resources:
  MoodleDataRoot:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: !Sub MoodleDataRoot-${EnvironmentName}

  MountTargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: MountTarget Security Group
      GroupName: !Sub MT-SecurityGroup-${EnvironmentName}
      VpcId:
        Fn::ImportValue: !Sub ${EnvironmentName}-VPC

  MountTargetSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-EC2SecurityGroup
      GroupId:
        Fn::GetAtt:
          - MountTargetSecurityGroup
          - GroupId

  MountTargetResource1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref MoodleDataRoot
      SubnetId:
        Fn::ImportValue: !Sub ${EnvironmentName}-PrivateSubnet1
      SecurityGroups:
        - !Ref MountTargetSecurityGroup

  MountTargetResource2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref MoodleDataRoot
      SubnetId:
        Fn::ImportValue: !Sub ${EnvironmentName}-PrivateSubnet2
      SecurityGroups:
        - !Ref MountTargetSecurityGroup
