AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
  MasterUserPassword:
    Description: A password
    Type: String

Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      DBSubnetGroupName:
        Fn::ImportValue: !Sub ${EnvironmentName}-MySQLSubnetGroup
      AllocatedStorage: '20'
      DBInstanceClass: db.t4g.micro
      Engine: MySQL
      MasterUsername: moodle
      MasterUserPassword: !Ref MasterUserPassword
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub ${EnvironmentName}-MySQLSecurityGroup
  
  MoodleDataRoot:
    Type: AWS::EFS::FileSystem
    DeletionPolicy: Retain
    Properties:
      BackupPolicy:
        Status: ENABLED
      Encrypted: true
      FileSystemTags:
        - Key: Name
          Value: !Sub MoodleDataRoot-${EnvironmentName}

  MountTargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: MountTarget Security Group
      GroupName: !Sub MT-SecurityGroup-${EnvironmentName}
      VpcId:
        Fn::ImportValue: !Sub ${EnvironmentName}-VPC

  MountTargetSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: -1
      FromPort: -1
      ToPort: -1
      SourceSecurityGroupId: 
        Fn::ImportValue: !Sub ${EnvironmentName}-EC2SecurityGroup
      GroupId:
        Fn::GetAtt:
          - MountTargetSecurityGroup
          - GroupId

  MountTargetResource1:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref MoodleDataRoot
      SubnetId:
        Fn::ImportValue: !Sub ${EnvironmentName}-PrivateSubnet1
      SecurityGroups:
        - !Ref MountTargetSecurityGroup

  MountTargetResource2:
    Type: AWS::EFS::MountTarget
    Properties:
      FileSystemId: !Ref MoodleDataRoot
      SubnetId:
        Fn::ImportValue: !Sub ${EnvironmentName}-PrivateSubnet2
      SecurityGroups:
        - !Ref MountTargetSecurityGroup

Outputs:
  MySQL:
    Description: A MySQL Url
    Value:
      Fn::GetAtt:
        - MyDB
        - Endpoint.Address
  
  FileSystem:
    Description: A file system id
    Value: !Ref MoodleDataRoot
    Export:
      Name: !Sub ${EnvironmentName}-FileSystemId
