AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  BucketName:
    Description: A bucket name
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName
  
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: PolicyForMoodle
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - Fn::Join:
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref Bucket
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource:
                  - Fn::Join:
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref Bucket
                      - '/*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonSSMPatchAssociation
      RoleName: !Sub RoleForMoodle-${EnvironmentName}

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub MoodleInstanceProfile-${EnvironmentName}
      Path: /
      Roles:
        - !Ref Role

Outputs:
  Bucket:
    Description: A bucket
    Value: !Ref Bucket
  
  InstanceProfile:
    Description: A reference to the instance profile
    Value:
      Fn::GetAtt:
        - InstanceProfile
        - Arn
    Export:
      Name: !Sub ${EnvironmentName}-InstanceProfile
  