AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  BucketName:
    Description: A bucket name
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref BucketName

Outputs:
  Bucket:
    Description: A bucket
    Value: !Ref Bucket
    Export:
      Name: !Sub ${EnvironmentName}-Bucket
 